[package]
name = "wiwi"
version = "0.5.4"
description = "A library, of, Stuff™"
edition = "2021"
authors = ["Meadowsys"]
repository = "https://github.com/meadowsys/wiwi.git"
license = "MIT"
keywords = [
	"decode",
	"encode",
	"hex",
	"z85"
]

[dependencies]
argon2 = { version = "0.5.3", optional = true }
cfg-if = "1.0.0"
chacha20poly1305 = { version = "0.10.1", optional = true }
chrono = { version = "0.4.35", optional = true, features = ["clock"] }
hashbrown = { version = "0.14.3", optional = true, features = ["ahash"] }
httparse = { version = "1.8.0", optional = true }
image = { version = "0.25.1", optional = true }
ordered-float = { version = "4.2.0", optional = true }
p384 = { version = "0.13.0", optional = true }
parking_lot = { version = "0.12.1", optional = true }
rand = { version = "0.8.5", optional = true }
serde_json = { version = "1.0.116", optional = true }
spin_sleep = { version = "1.2.0", optional = true }
thiserror = { version = "1.0.58", optional = true }
tokio = { version = "1.36.0", optional = true, features = ["full"] }
url = { version = "2.5.0", optional = true }
uuid = { version = "1.8.0", optional = true }
zeroize = { version = "1.7.0", optional = true }

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
hex = "0.4.3"
z85 = "3.0.5"

[features]
# Make sure to check README and workflow files too
# Also check below, docs.rs config

unstable = []

auth = [
	"dep:argon2",
	"dep:chacha20poly1305",
	"dep:chrono",
	"dep:p384",
	"dep:rand",
	"dep:thiserror",
	"dep:zeroize",
	"z85"
]
# base16 = [
# 	"dep:thiserror",
# 	"hex"
# ]
# base32 = [
# 	"dep:thiserror"
# ]
# base64 = [
# 	"dep:thiserror"
# ]
clock-timer = [
	"dep:chrono",
	"dep:thiserror"
]
clock-timer-2 = [
	"dep:chrono"
]
debounce = [
	"dep:chrono"
]
h = [
	"dep:thiserror"
]
hex = [
	"dep:thiserror"
]
id = [
	"dep:rand"
]
lazy-wrap = [
	"dep:parking_lot"
]
lsl = [
	"dep:hashbrown",
	"dep:spin_sleep",
	"dep:uuid",
	"hex",
	"id"
]
serialiser = [
	"dep:ordered-float"
]
string-pool = [
	"dep:hashbrown",
	"lazy-wrap"
]
# ws = [
# 	"dep:httparse",
# 	"dep:thiserror",
# 	"dep:url"
# ]
z85 = [
	"dep:thiserror"
]

# addon features
hashbrown = ["dep:hashbrown"]
image = ["dep:image"]
serde-json = ["dep:serde_json"]

# runtime selection features
tokio = ["dep:tokio"]

# config options for certain features
# compiler errors if the feature its for isn't enabled
debounce-dyn-fn = []

[[bench]]
name = "hex-and-z85"
harness = false

[profile.bench]
lto = "thin"

[package.metadata.docs.rs]
# https://docs.rs/about/metadata

# all features, and only tokio for runtime feature
features = [
	"clock-timer-2",
	"debounce",
	"h",
	"hex",
	"lazy-wrap",
	"lsl",
	"serialiser",
	"string-pool",
	"z85",

	"tokio",

	"image"
]

targets = [
	"aarch64-apple-darwin",
	"x86_64-apple-darwin",
	"x86_64-unknown-linux-gnu",
	"x86_64-pc-windows-msvc"
]

[workspace]
members = [
	"scripts"
]
