[package]
name = "wiwi"
version = "0.0.0"
description = "A library, of, Stuff™"
edition = "2021"
authors = ["Meadowsys"]
repository = "https://github.com/Meadowsys/wiwi.git"
license = "MIT"

[dependencies]
parking_lot = "0.12.1"
