[package]
name = "wiwi"
version = "0.0.0"
description = "A library, of, Stuff™"
edition = "2021"
authors = ["Meadowsys"]
repository = "https://github.com/Meadowsys/wiwi.git"
license = "MIT"

[dependencies]
cfg-if = "1.0.0"
parking_lot = { version = "0.12.1", optional = true }

[features]
lazy-wrap = ["dep:parking_lot"]
