[package]
name = "wiwi-wasm"
description = "Nicer, higher level APIs for working with JavaScript from Rust (WASM)"
version = "0.0.0-reserved"
authors = ["Meadow Liu <meadowsys@kiwin.gay>"]
repository = "https://github.com/meadowsys/wasm-builders"
license = "MIT"
edition = "2024"
rust-version = "1.85"
exclude = [
	".cargo",
	".github",
	".gitignore",
	"rust-toolchain.toml"
]

[dependencies]
wasm-bindgen = { version = "0.2.100", default-features = false, features = ["msrv"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.50"

[features]
default = [
	"std"
]
std = [
	"wasm-bindgen/std"
]

[package.metadata.docs.rs]
# https://docs.rs/about/metadata

rustdoc-args = [
	"--cfg",
	"docsrs"
]
features = [
	"std"
]
targets = [
	"wasm32-unknown-unknown",
	"wasm32-wasip2",
	"aarch64-apple-darwin"
]
