[package]
name = "js-builders"
description = "Builders for JavaScript objects and methods in Rust (WASM)"
version = "0.0.0-reserved"
authors = ["Meadow Liu <meadowsys@kiwin.gay>"]
repository = "https://github.com/meadowsys/wasm-builders"
license = "MIT"
edition = "2024"
rust-version = "1.85"
exclude = [
	".gitignore",
	"rust-toolchain.toml"
]

[dependencies]
# js-sys = { version = "0.3.77", default-features = false }
wasm-bindgen = { version = "0.2.100", default-features = false, features = ["msrv"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.50"

[features]
default = [
	"std"
]
std = [
	"wasm-bindgen/std"
]
