[package]
name = "wiwi"
version = "0.0.0"
description = "A library, of, Stuff™"
edition = "2021"
authors = ["Meadowsys"]
repository = "https://github.com/Meadowsys/wiwi.git"
license = "MIT"

[dependencies]
cfg-if = "1.0.0"
hashbrown = { version = "0.14.3", optional = true }
parking_lot = { version = "0.12.1", optional = true }

[dev-dependencies]
rand = "0.8.5"

[features]
lazy-wrap = ["dep:parking_lot"]
string-pool = ["dep:hashbrown", "lazy-wrap"]
