[package]
name = "wiwi-scripts"
version = { workspace = true }
edition = { workspace = true }
publish = false

[dependencies]
wiwi = { path = ".." }

[[bin]]
name = "generate-hex-table-decoder"

[[bin]]
name = "generate-z85-table-decoder"
