name: clippy
on:
  workflow_call:
  workflow_dispatch:

jobs:
  run:
    name: run
    runs-on: macos-14

    steps:
    - name: checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: setup rust
      run: rustc --version

    - name: run clippy
      run: |
        cargo clippy --verbose -- --deny warnings
