name: clippy
on:
  workflow_call:
  workflow_dispatch:

jobs:
  run:
    name: run
    runs-on: macos-14

    steps:
    - name: checkout code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: setup rust
      run: rustc --version

    - name: run clippy
      run: |
        cargo clippy --verbose --features all-unstable,all-addons -- --deny warnings
