name: clippy
on:
  workflow_call:
    inputs:
      error-on-warn:
        description: If warnings should become errors (and fail CI)
        default: true
        type: boolean
  workflow_dispatch:

jobs:
  run:
    name: run
    runs-on: macos-14

    steps:
    - name: checkout code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: setup rust
      run: rustc --version

    - name: run clippy
      run: |
        if [ ${{ inputs.error-on-warn }} ]; then
          cargo clippy --verbose --features all-unstable,all-addons -- --deny warnings
        else
          cargo clippy --verbose --features all-unstable,all-addons
        fi
