name: feature check
on:
  workflow_call:

jobs:
  run:
    name: run
    runs-on: macos-14

    steps:
    - name: checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: setup rust
      run: rustc --version

    - name: install cargo-hack
      run: cargo install cargo-hack --verbose

    - name: check features individually
      run: cargo hack check --verbose --each-feature --skip omega-tuples-of-doom

    - name: test features individually
      run: cargo hack test --verbose --each-feature --skip omega-tuples-of-doom
