name: feature check
on:
  workflow_call:

jobs:
  run:
    name: run
    runs-on: macos-14

    steps:
    - name: checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: setup rust
      run: rustc --version

    - name: install cargo-hack
      run: cargo install cargo-hack
      env:
        # try speed it up a little bit
        # cargo-hack doesn't need to be omega performance,
        # compile time matters more here
        RUSTFLAGS: -Copt-level=1 -Clto=false -Ccodegen-units=256

    - name: check features individually
      run: cargo hack check --each-feature
