name: publish

on:
  push:
    tags:
    - "v*.*.*"

jobs:
  test:
    name: test
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        featureflags:
        - --features clock-timer,h,lazy-wrap,string-pool,tokio

    steps:
    - name: checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: setup rust
      run: rustc --version

    - name: build
      run: cargo build --release --verbose ${{ matrix.featureflags }}

    - name: test
      run: cargo test --release --verbose ${{ matrix.featureflags }}

  publish:
    name: publish crate
    needs: test
    runs-on: ubuntu-22.04

    steps:
    - name: checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: setup rust
      run: rustc --version

    - name: publish
      run: cargo publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
