name: publish

on:
  push:
    tags:
    - "v*.*.*"

jobs:
  publish:
    name: publish crate
    runs-on: ubuntu-22.04

    steps:
    - name: checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: setup rust
      run: rustc --version

    - run: cargo build --all-features --verbose
    - run: cargo build --all-features --release --verbose
    - run: cargo test --all-features --verbose
    - run: cargo test --all-features --release --verbose

    - name: dry run publish
      run: cargo publish --dry-run

    - name: upload crate artifact
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
      with:
        name: crate
        path: target/package/*.crate

    - name: publish
      run: cargo publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
