name: publish
on:
  push:
    tags:
    - "v*.*.*"

jobs:
  test:
    name: test
    runs-on: ${{ matrix.runs-on }}

    strategy:
      fail-fast: false
      matrix:
        featureflags:
        # Make sure to check README and Cargo.toml too
        - all
        - all,debounce-dyn-fn

        runs-on:
        - ubuntu-22.04
        - ubuntu-24.04
        - macos-14

    steps:
    - name: checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: setup rust
      run: rustc --version

    - name: build
      run: cargo build --release --verbose --features ${{ matrix.featureflags }}

    - name: test
      run: cargo test --verbose --features ${{ matrix.featureflags }}
    - name: test in release
      run: cargo test --release --verbose --features ${{ matrix.featureflags }}

  feature-check:
    uses: ./.github/workflows/feature-check.yml

  publish:
    name: publish crate
    needs:
    - test
    - feature-check
    runs-on: macos-14

    steps:
    - name: checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: setup rust
      run: rustc --version

    - name: publish macro crate
      working-directory: macro
      run: cargo publish --verbose
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

    - name: publish
      run: cargo publish --verbose
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
