name: publish
on:
  push:
    tags:
    - "v*.*.*"

jobs:
  test:
    name: test
    runs-on: ${{ matrix.runs-on }}

    strategy:
      fail-fast: false
      matrix:
        runs-on:
        - ubuntu-22.04
        - ubuntu-24.04
        - macos-14

    steps:
    - name: checkout code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: setup rust
      run: rustc --version

    - name: build
      run: cargo build --verbose --features all,all-addons
    - name: build in release
      run: cargo build --release --verbose --features all,all-addons

    - name: test
      run: cargo test --verbose --features all,all-addons
    - name: test in release
      run: cargo test --release --verbose --features all,all-addons

  clippy:
    uses: ./.github/workflows/clippy.yml

  feature-check:
    uses: ./.github/workflows/feature-check.yml

  verify-gen-features:
    uses: ./.github/workflows/verify-gen-features.yml

  publish:
    name: publish crate
    runs-on: macos-14
    needs:
    - test
    - feature-check
    - verify-gen-features

    steps:
    - name: checkout code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: setup rust
      run: rustc --version

    - name: publish macro crate
      working-directory: macro
      run: cargo publish --verbose
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

    - name: publish
      run: cargo publish --verbose
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
