name: publish
on:
  push:
    tags:
    - "v*.*.*"

jobs:
  test:
    name: test
    runs-on: ${{ matrix.runs-on }}

    strategy:
      fail-fast: false
      matrix:
        runs-on:
        - ubuntu-22.04
        - ubuntu-24.04
        - macos-14

    steps:
    - name: checkout code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: setup rust
      run: rustc --version

    - name: build
      run: cargo build --verbose
    - name: build in release
      run: cargo build --release --verbose

    - name: test
      run: cargo test --verbose
    - name: test in release
      run: cargo test --release --verbose

  clippy:
    uses: ./.github/workflows/clippy.yml

  publish:
    name: publish crates
    runs-on: macos-14
    needs:
    - test
    # TODO enable when existing warnings have been cleared
    # - clippy

    steps:
    - name: checkout code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: setup rust
      run: rustc --version

    - name: publish macro crate
      working-directory: macro
      run: cargo publish --verbose
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

    - name: publish
      run: cargo publish --verbose
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
