name: publish
on:
  push:
    tags:
    - "v*.*.*"

jobs:
  test:
    name: test
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        featureflags:
        # Make sure to check README and Cargo.toml too
        - clock-timer-2,debounce,h,hex,lazy-wrap,serialiser,string-pool,z85
        - clock-timer-2,debounce,h,hex,lazy-wrap,serialiser,string-pool,z85,debounce-dyn-fn

        runtimes:
        - tokio

    steps:
    - name: checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: setup rust
      run: rustc --version

    - name: build
      run: cargo build --release --verbose --features ${{ matrix.featureflags }} --features ${{ matrix.runtimes }}

    - name: test
      run: cargo test --verbose --features ${{ matrix.featureflags }} --features ${{ matrix.runtimes }}
    - name: test in release
      run: cargo test --release --verbose --features ${{ matrix.featureflags }} --features ${{ matrix.runtimes }}

  publish:
    name: publish crate
    needs: test
    runs-on: ubuntu-22.04

    steps:
    - name: checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: setup rust
      run: rustc --version

    - name: publish
      run: cargo publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
