name: tests
on:
  push:
    branches:
    - "**"

env:
  RUSTFLAGS: "-Cinstrument-coverage -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code"

jobs:
  test:
    name: run
    runs-on: ${{ matrix.runs-on }}

    strategy:
      fail-fast: false
      matrix:
        runs-on:
        - ubuntu-22.04
        - ubuntu-24.04
        - macos-14

    steps:
    - name: checkout code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: setup rust
      run: rustc --version

    - name: build
      run: cargo build --verbose --features all-unstable,all-addons

    - name: test
      run: cargo test --verbose --features all-unstable,all-addons
      env:
        CARGO_INCREMENTAL: "0"
        LLVM_PROFILE_FILE: "target/coverage/test-%m-%p.profraw"

    - name: fetch/run grcov
      run: |
        platform=$(uname)
        case $platform in
          Darwin)
            # macos-14 runners run on apple silicon, so aarch64
            curl -Lo grcov.bz2 https://github.com/mozilla/grcov/releases/download/v0.8.19/grcov-aarch64-apple-darwin.tar.bz2
            ;;
          Linux)
            curl -Lo grcov.bz2 https://github.com/mozilla/grcov/releases/download/v0.8.19/grcov-x86_64-unknown-linux-musl.tar.bz2
            ;;
          *)
            echo weird
            exit 1
            ;;
        esac

        tar xvf grcov.bz2
        rm grcov.bz2

        ./grcov . -s . -t lcov --binary-path ./target/debug/ --branch --ignore-not-existing -o ./target/coverage/tests.lcov

    - name: upload to codecov
      uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4.5.0
      with:
        files: target/coverage/*.lcov
        token: ${{ secrets.CODECOV_TOKEN }}

  feature-check:
    uses: ./.github/workflows/feature-check.yml

  verify-gen-features:
    uses: ./.github/workflows/verify-gen-features.yml
