name: verify generated features
on:
  workflow_call:
  workflow_dispatch:

jobs:
  run:
    name: run
    runs-on: macos-14

    steps:
    - name: checkout code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: setup rust
      run: rustc --version

    - name: run gen-features script
      run: ./scripts/gen-features

    # if there are git changes, files are not up to date, and we error
    - name: verify generated features are up to date
      run: git diff --exit-code && git diff --exit-code --cached
